### ISSUE TITLE
Erro no upload

### ISSUE THREAD

**Issue by Joab0** [squarecloudofc/wrapper-api-py#4]
Ao tentar enviar uma aplicação sem uma descrição no arquivo de configuração, acontece o seginte erro:
```
TypeError: UploadData.__init__() missing 1 required positional argument: 'description'
```

**Comment by Robert-Nogueira** [comment]
Aparentemente a resposta da rota upload simplesmente não ta incluindo o campo description, ao invés de vir porém com o valor null(como é nas outras rotas), então ao passar `**data` pro construtor de UploadData gera esse erro.

Defini None como um valor padrão, vou aproveitar e checar as outras rotas
```python
@dataclass
class UploadData:
    id: str
    tag: str
    language: str
    avatar: str
    ram: int
    cpu: int
    subdomain: str | None = None
    description: str | None = None
```
obrigado por reportar o erro 👋
