### ISSUE TITLE
Problemas no código da biblioteca

### ISSUE THREAD

**Issue by Joab0** [squarecloudofc/wrapper-api-py#8]
Durante o desenvolvimento de um gerenciador de aplicações, identifiquei alguns problemas no código da biblioteca que gostaria de destacar:

- **Construtor de `Client` com Parâmetro `debug` Padrão:** Atualmente, o construtor de `Client` recebe um argumento `debug`, que por padrão é `True`. Como o modo debug é mais relevante apenas em desenvolvimento, sugiro alterar o padrão para `False`, outra alternativa seria alterar a estrutura do logger, permitindo que cada módulo tenha um logger individual (`log = logging.getLogger(__name__)`), assim, para ativar o debug da biblioteca bastaria usar `logging.getLogger("squarecloud").setLevel(logging.DEBUG)`.

- **Repetição de Código:** Há uma repetição excessiva de código relacionado ao listener em todos os métodos do `Client`, o que vai contra o princípio [DRY](https://en.m.wikipedia.org/wiki/Don%27t_repeat_yourself). Uma solução mais eficiente seria criar uma função dedicada para lidar com o listener, reduzindo significativamente o tamanho do código e evitando problemas associados à repetição excessiva.

- **Tipagem Ruim:** A biblioteca apresenta casos onde a tipagem não está bem definida, incluindo situações em que a resposta bruta da API é utilizada.

 
- **Documentação Excessiva:** O código tem uma quantidade significativa de docstrings desnecessárias (em métodos mágicos e funções internas por exemplo), o que deixa o código mais confuso de se ler.

Estou disponibilizando essas observações nesta issue, pois, embora eu não tenha tempo para criar um PR no momento, gostaria de contribuir para a melhoria da biblioteca.  Se precisar de ajuda, dicas ou sugestões, sinta-se a vontade de me chamar no Discord (joab0).

**Comment by Robert-Nogueira** [comment]
Olá, boa noite,

Quanto ao logger, já tenho planos de refatorar completamente o sistema de logs na próxima versão, que será lançada em breve.

Em relação aos listeners, reconheço a presença de uma repetição desnecessária nos métodos e pretendo fazer uma revisão.

No que diz respeito às docstrings, considero fundamental documentar todas as partes do código. Posso reescrever algumas seções para tornar a visualização menos "poluída", mas não vejo razão para removê-las.

Quanto às tipagens, imagino que esteja falando sobre casos em que algo na resposta dos endpoints mudam, mas eu opto por manter as tipagens com Pydantic devido às vantagens oferecidas. Pydantic proporciona validação automática de dados, facilita a serialização, torna o código mais claro e legível, simplifica a manutenção com mensagens de erro úteis e integra-se bem com ferramentas de desenvolvimento como o Mypy. Isso garante uma experiência de desenvolvimento mais eficiente e robusta. Além disso, se o projeto estiver associado a ecossistemas que favorecem o uso do Pydantic, como o FastAPI, isso pode ser uma vantagem significativa para quem usa a lib.

**Comment by Joab0** [comment]
Boa noite. Sobre as docstrings, nem tudo no código precisa ser documentado, de fato isso é útil, um programador iniciante consegue entender facilmente o código, porém, como falei acima, isso acaba deixando o código com excesso de documentação, o que piora a visualização. Sobre a tipagem, Pydantc é de fato uma opção muito boa, mas me refiro a trechos de código com tipagem genérica, por exemplo: https://github.com/squarecloudofc/wrapper-api-py/blob/main/squarecloud%2Fdata.py#L29-L30, https://github.com/squarecloudofc/wrapper-api-py/blob/main/squarecloud%2Fdata.py#L37 e https://github.com/squarecloudofc/wrapper-api-py/blob/main/squarecloud%2Fdata.py#L73.

**Comment by Robert-Nogueira** [comment]
Em relação às docstrings, concordo com sua perspectiva sobre o equilíbrio entre documentação e visualização do código. Vou revisar as docstrings para garantir que forneçam informações essenciais sem excessos.
Quanto à tipagem, entendi seu ponto em relação aos trechos específicos do código que mencionou. Irei analisar e ajustar a tipagem.

Se houver mais pontos específicos que gostaria de discutir, por favor, sinta-se à vontade para compartilhar.
